### ISSUE TITLE
Output Rendering Misalignment

### ISSUE THREAD

**Issue by dreamiter** [microsoft/vscode-notebook-renderers#101]
Hi This is potentially not a bug nor an issue. But since I upgraded my Mac OS to Monterey version, the rendering is now somehow giving me issues.

My Mac:
```
  System Version:	macOS 12.2.1 (21D62)
  Kernel Version:	Darwin 21.3.0
  Boot Volume:	Macintosh HD
```

pd.Series misalignment:
`df_raw['CONVERTED_PCT_T12'].describe()`

count    5300.000000
mean        0.005806
std         0.024838
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         0.285714

<img width="373" alt="Screen Shot 2022-03-09 at 11 48 12 PM" src="https://user-images.githubusercontent.com/9292401/157591773-ba05edea-609c-4d26-8294-0c0b0a15cef5.png">

**Comment by DonJayamanne** [comment]
Closing as fixed, this has been fixed in the latest VS Code insiders release
