### ISSUE TITLE
Plotly.js needs update

### ISSUE THREAD

**Issue by jackthepanisher** [microsoft/vscode-notebook-renderers#102]
## Environment data

-   VS Code version: 1.65.2
-   Jupyter Extension version: v2022.2.1030672458
-   Jupyter Notebook Renderers: v1.0.6
-   OS and version: Windows 10
-   Python version: 3.9.9
-   Type of virtual environment: NA
-   Jupyter server running: Local

## Expected behaviour

Full functionality of latest Plotly Python package is available in VS code / Jupyter, i.e. text labels on heatmap segments are working when running with Plotly version 5.5.0+.

## Actual behaviour

The example from https://plotly.com/python/heatmaps/#text-on-heatmap-points does not show the text labels in each color block when running in VS Code / Jupyter with the `vscode` renderer. It does show the labels when using the `notebook` renderer which uses the Plotly.js from the Python package.

## Steps to reproduce:

```Python
import plotly.graph_objects as go

fig = go.Figure(data=go.Heatmap(
                z=[[1, 20, 30],
                  [20, 1, 60],
                  [30, 60, 1]],
                text=[['one', 'twenty', 'thirty'],
                      ['twenty', 'one', 'sixty'],
                      ['thirty', 'sixty', 'one']],
                texttemplate="%{text}",
                textfont={"size":20}))

fig.show()
```

## Details

It looks like the Plotly.js version shipped with Jupyter Notebook Renderers is still version 2.7.0 while Plotly 5.5.0 was released with Plotly.js 2.8.3 and Plotly 5.6.0 (currently latest) was released with Plotly.js 2.9.0.

**Comment by DonJayamanne** [comment]
@jackthepanisher 

Fixed in the PR 
![image](https://user-images.githubusercontent.com/1948812/158481793-87159c1b-ea83-4bee-848a-15b4fb1ff620.png)

**Comment by DonJayamanne** [comment]
Will publish a release soon, probably next week along with the next version of Jupyter extension.

**Comment by jackthepanisher** [comment]
@DonJayamanne just checking if this has not been slipped.
