### ISSUE TITLE
How to source a .sh file in Jupyter notebook?

### ISSUE THREAD

**Issue by m3lab-zzl** [microsoft/vscode-notebook-renderers#109]
Hello.

I want to source a .sh file to load some environmental variables, it works fine in zsh, but not working in Jupyter notebook.

`source /opt/intel/oneapi/setvars.sh`

Could you please help me load environmental variables into jupyter notebook, so that I can execute command just like in the zsh command line?

Many thanks.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue,
I'm assuming you are using a Python kernel.
If you want to load env variables into a Jupyter notebook, then the only way to do that reliably is by creating a `.env` file and adding the env variables into that.
* Open a workspace folder
* Create a file named `.env` and add variables as follows, each in a new line
```
HELLO_WORLD=1234
FOO=bar
```
*   When you run the kernel the variables would have loaded.

Sourcing `.sh` files will not work as the Python kernle only loads those into a shell context and not into the current process. Unfortunately that's how IPyKernel works and is beyond the control of the Jupyter extension in VS Code.
I don't think you could even load such .sh files in Jupyter either.

> so that I can execute command just like in the zsh command line?

Running regular zsh commands can be done by just prefixing the line with `!` and running in a python cell
E.g. as follows
```python
!echo "Hello World"
```
or 
```python
!ls
```

This will run your regular shell commands in a notebook cell from within Python.
However its not a persistent shell, hence any variables declared or env variables loaded will not be persisted.
