### ISSUE TITLE
Render existing notebooke not render right

### ISSUE THREAD

**Issue by amirhp110** [microsoft/vscode-notebook-renderers#117]
Here are two examples that you can try:
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py
https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py

**Comment by DonJayamanne** [comment]
This should now be fixed, please feel free to re-open or file a new issue if this or similar issues eixst.
