### ISSUE TITLE
Adopt onRenderer implicit activation event

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-notebook-renderers#150]
Re https://github.com/microsoft/vscode/issues/167961, we could potentially remove `onNotebook:*` since the extension will be activated when the core decides to use the renderer. It will wait until we have the newer Insiders.

**Comment by joyceerhl** [comment]
You can just declare `activationEvents` to be an empty array

**Comment by joyceerhl** [comment]
Maybe an issue for https://github.com/microsoft/vscode-vsce assuming this repros against latest `vsce` since I believe not passing `activationEvents` at all is actually supported in VS Code itself
