### ISSUE TITLE
Error: "The installed version of the Renderer Extension is outdated [...]" even though it is up to date.

### ISSUE THREAD

**Issue by ruilvo** [microsoft/vscode-notebook-renderers#153]
Type: <b>Bug</b>

Hello,

On a Jupyter notebook, I have the following in the first cell:

```py
%matplotlib widget
```

When I try to run a cell that actually wants to display a plot, I'm presented with the following error:

```txt
The installed version of the Renderer Extension is outdated and requires an update to view IPyWidgets. 
Click Yes to open Jupyter Notebook Renderer Extension installation page. 
```

I have automatic updates on all extensions, so it's not out of date. 

Relevant extensions:

Extension | Author (truncated) | Version
-- | -- | --
isort | ms- | 2023.9.10461023
pylint | ms- | 2023.3.10391012
python | ms- | 2023.3.10461028
vscode-pylance | ms- | 2023.2.20
jupyter | ms- | 2023.2.1000471055
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.14
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-powertoys | ms- | 0.0.6
vscode-jupyter-slideshow | ms- | 0.1.5

Extension version: 1.0.14
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.36GB (5.78GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 5fb2a04f-d73a-4990-ab57-e4870467f19e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12:30657548
2i9eh265:30646982
vsctsb:30662444
vscodeenable:30660116

```

</details>

**Comment by ruilvo** [comment]
Okay, experimenting a bit, I noticed couple things:

The [version history](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers&ssr=false#version-history) shows version 1.015 is available. 

I downloaded the `vsix` and tried to install it, but it said it's not compatible with my version of VSCode. 

Then I remembered I had enabled pre-releases on my Jupyter extension pack (`ms-toolsai.jupyter`). 
I reverted to stable and all is fine now.

Seems the problem is something was broken between using a stable release of VSCode and a pre-release version of the Jupyter pack.

**Comment by DonJayamanne** [comment]
thanks for filling this issues
You are using the latest pre-release version of the Jupyter extension, and in order to get ipywidgets working you will need to install vscode insiders with the latest pre-release version of Jupiter and latest version of notebook renderer extension

This is only temporary, the next stacks release will be in approx 2 weeks
