### ISSUE TITLE
IPyWidgets not working with Jupyter Kernel

### ISSUE THREAD

**Issue by JanMueGo** [microsoft/vscode-notebook-renderers#155]
VS Code Version: 1.75.1 (Universal)

Whenever I am using sth with ipywidgets in a jupyter notebook in VS code, I get the notification from the screenshot that says: "The installed version of the Renderer Extension is outdated and required and update to view IPyWidgets. Click Yes to open Jupyter Notebook Renderer Extension installation page." However, I already have the latest version and tried multiple other version but nothing changes. Other than that there is no error message or something, the widget is simply not displayed. But it blocks the whole notebook because it's stuck with the command where the widget should be generated.

I already tried a lot, downgrading libraries etc but cannot make it work.
Easy example to trigger the bug:
```
import ipywidgets as widgets


def run(a, b):
    print(f"Slider : {a}\nDropdown : {b}")

widgets.interact(
    run,
    a=widgets.IntSlider(
        value=1,
        min=1,
        max=3,
        step=1,
        description="Slider :",
    ),
    b=widgets.Dropdown(
        options=["1", "2", "3"],
        value="2",
        description="Dropdown :",
        disabled=False,
    ),
)
```

![Bildschirm­foto 2023-02-24 um 08 27 15](https://user-images.githubusercontent.com/97528359/221118053-ba8aab74-7462-4140-ba21-52cf50518670.png)

I am using pipenv to handle the venv:
`pipenv run jupyter --version`
Output:
Selected Jupyter core packages...
IPython          : 8.10.0
ipykernel        : 6.21.2
ipywidgets       : 7.7.3
jupyter_client   : 8.0.3
jupyter_core     : 5.2.0
jupyter_server   : 2.3.0
jupyterlab       : 3.6.1
nbclient         : 0.7.2
nbconvert        : 7.2.9
nbformat         : 5.7.3
notebook         : 6.5.2
qtconsole        : not installed
traitlets        : 5.9.0

**Comment by DonJayamanne** [comment]
Looks like you are using the pre-release version of Jupyter extension
To use ipywidhets with the prerelease version please install vscode insiders
Or please wait for the next stable release which will be some time next week

**Comment by JanMueGo** [comment]
Thanks for the fast reply!
Which extension exactly do you mean? Are you referring to the jupyterlab version?
If yes, I could probably also easily downgrade that. Was not aware that this is a pre-released version 🤔

**Comment by JanMueGo** [comment]
Thanks for the fast reply @DonJayamanne! Much appreciated!
