### ISSUE TITLE
is there documentation?

### ISSUE THREAD

**Issue by pelikhan** [microsoft/vscode-notebook-renderers#162]

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, not sure what you mean by documentation
This extension is used to render outputs for Jupyter Notebooks in VS Code
Uses the VS Code API to contribute renderers for different mime types

Perhaps you are running into some issue hence looking for some documentation
Pelase could you describe the reason why you are looking for documentation, is it to contribute or to figure out what this extension does (perhaps you are new to Jupyter Notebooks or the like)

**Comment by pelikhan** [comment]
Which renderer are you adding? How do we use this in a notebook?

**Comment by DonJayamanne** [comment]
You do not need to do anyting specific to use renderers in a notebook.
If you run a cell in Jupyter and you get output such as text/html, then vscode will select a text/html rendere and display that.
This extension supports renderers for gif, png, jpg, svg, vega, plotly and other mime types.
Png, svg renderers are already supported in vscode, however jupyter ntoebooks might require addtional changes, hence the custom renderers

Again this only applies to Jupyter notebooks in VS Code

**Comment by DonJayamanne** [comment]
> Which renderer are you adding?

Will update the REDME to document this.

**Comment by iamhammer** [comment]
Is there a way to render SQL Output (or CSV) in a grid view?

**Comment by DonJayamanne** [comment]
> Is there a way to render SQL Output (or CSV) in a grid view?

Unfortunately no, you might want to look for other VS Code extensions or jupyter notebook magics or packages that make this possible.

**Comment by ToON-01** [comment]
oidkksjyeootiugkopuflskks;;

**Comment by ToON-01** [comment]
kkoiuyfpiuelsbbioeus
@dnfclas slall

**Comment by ToON-01** [comment]
uuuuuuuu
