### ISSUE TITLE
after update vscode to 1.81.0, %matplotlib widget not usable

### ISSUE THREAD

**Issue by Foristkirito** [microsoft/vscode-notebook-renderers#172]
only a blank appear
![image](https://github.com/microsoft/vscode-notebook-renderers/assets/13299109/26fed220-03c4-489a-8c8f-1b3aafb55561)

**Comment by JotaRata** [comment]
bump

**Comment by DonJayamanne** [comment]
Sorry got not getting back on this issue, are you still running into this issue?
