### ISSUE TITLE
[docs] Help: Linking up the development build

### ISSUE THREAD

**Issue by rgbkrk** [microsoft/vscode-notebook-renderers#181]
I've followed the contributing docs to get the local dev build going. However, I can't seem to activate the local extension. Can the contributing guidelines give a bit more on how to get this package going? I'd love to fix several mimetypes.

**Comment by rgbkrk** [comment]
It looks like the next step is to open `src/extension/index.ts` and hit F5 (...I wish I knew what the command palette was for this, as not all keyboards have F5).

**Comment by DonJayamanne** [comment]
## Local Debugging

1. From the debug panel select `Run Extension`
    Note: This will automatically start the incremental build task.
    Optionally, use the command `Debug: Select and Start Debugging -> Run Extension`
2. Once VS Code launches, open a notebook file (`.ipynb`) with output for one of the mime types supported by this extension (such as `application/vnd.vega.v2+json`)

**Comment by DonJayamanne** [comment]
Closing as fixed.
