### ISSUE TITLE
High IDL CPU Consumption

### ISSUE THREAD

**Issue by MesoBolt** [microsoft/vscode-notebook-renderers#193]
Type: <b>Bug</b>

Hey there,

with the help of vscode "Help: Start Extension Bisect" I found out that the above extension seems to be the reason for a very high CPU consumption during idl. I did not run any script but just had ipynb files open and all my CPU cores were used at very high percentage for a longe time.

Kind regards
Marius

Extension version: 1.0.17
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'ssh-remote+mogon' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.30GB free)|
|Process Argv|--crash-reporter-id 2ec5ec3d-1115-444e-9f5c-101ba0c214db|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+mogon' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
edj9j583:30969295
7j2b6412:30969109

```

</details>

**Comment by DonJayamanne** [comment]
> just had ipynb files open and all my CPU cores were used at very high percentage for a longe 

play can you upload the notebook with the outputs as is

**Comment by MesoBolt** [comment]
I don't think I can do this because the notebook is pretty large and contains code and data I am not allowed to share open source. 

But I can tell you that I am saving figures in for loops multiple times and use my own defined classes from a separate file, where I close all plot instances before entering a new cell with a loop to save figures. After every for loop the last saved figure is shown in the notebook.

Now I disabled this extension. Without having the CPU issue anymore, everything else still works, also the preview of the last saved images. What is this extension explicitly for?

**Comment by DonJayamanne** [comment]
> Without having the CPU issue anymore, everything else still works, also the preview of the last saved images. What is this extension explicitly for?

This is responsible for rendering outputs, images and the like.
And also widgets.
Is it possible to remove the code, or replace it with some garbage string and replace the data (images/output) with some other random data/image, 
having a notebook would really help, else its not easy to identify the issue as we cannot replicate it at our end.

**Comment by DonJayamanne** [comment]
Closing this issue due to the fact that its been a few months since the last request for information.
