### ISSUE TITLE
Replacing requirejs dependency with modern es6 imports

### ISSUE THREAD

**Issue by marthacryan** [microsoft/vscode-notebook-renderers#223]
For a bit more context: https://github.com/requirejs/r.js/blob/1874a29ad51a395703629e3aece5d094a791b7ea/SECURITY.md

Requirejs is no longer actively maintained, and can be replaced with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules. 

For example, see our removal of requirejs in `plotly.py` here: https://github.com/plotly/plotly.py/pull/4763

**Comment by DonJayamanne** [comment]
Thanks for the heads up.
Not sure we can remove `requirejs` just yet, as ipywidgets depends on this, also the Renderers extension supports users with IPyWidgets 7 as well.
From what I understand, keeping requirejs should not break plotly or anything else.

Basically all we'd need to do in this extension is ship the latest version of plotly, isn't that right?

**Comment by gvwilson** [comment]
Thanks very much @DonJayamanne - much appreciated.

**Comment by DonJayamanne** [comment]
> Basically all we'd need to do in this extension is ship the latest version of plotly, isn't that right?

Please see my last comment here https://github.com/microsoft/vscode-notebook-renderers/issues/223#issuecomment-2450804059
@marthacryan /cc

**Comment by marthacryan** [comment]
I think this was more of a best practices thing than a blocker for anything plotly so I can close this if there's a good reason you still use it!
