### ISSUE TITLE
Do Not See nteract Rendering

### ISSUE THREAD

**Issue by Eddie-Hartman** [microsoft/vscode-notebook-renderers#79]
Hello.

I followed this post https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/#querying-and-visualizing-data
and was able to query some data in my database. Unfortunately, it doesn't appear to be rendering with nteract as described.

>The results of the query are displayed using the nteract Data Explorer,providing a rich interactive filter and visualization experience where the user can explore their data in a number of ways.

Can anyone point me in the right direction here? I just see results as essentially an HTML table and the only other option is csv, but there appear to be no renderers available for that.

![image](https://user-images.githubusercontent.com/14089997/142567804-f2b713ff-b416-428e-907e-0dbaed84748d.png)

Thank you.

**Comment by DonJayamanne** [comment]
Thanks for thinking this issue..
I've created an issue in .net repo, they should be able to help you with this. 
https://github.com/dotnet/interactive/issues/1780

**Comment by Eddie-Hartman** [comment]
Thank you.
