### ISSUE TITLE
Outdated CONTRIBUTING docs

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode-notebook-renderers#96]
Hi there 👋 !

I wanted to build the extension on my own today, but noticed the [CONTRIBUTING file](https://github.com/microsoft/vscode-notebook-renderers/blob/main/CONTRIBUTING.md) is still mentioning Node 12 and npm 6, which do not work when setting up.

As stated previously, I tried building the extension, although it was successful at the end sometimes, I got timeouts and sometimes npm parse errors, it seems building as per the docs only works on Node 14. Maybe the package JSON should be updated to v2? I could not get the build to work when not installing deps cleanly, which might be a bug, or a feature 😄.

PS: maybe would be also useful to publish releases and add the `.vsix` file assets to them as file assets for easy download and debugging. I would love to help out with a workflow for this, but I am not sure how it might conflict with #25.

**Comment by filiptronicek** [comment]
cc @DonJayamanne 👀

**Comment by DonJayamanne** [comment]
> le assets to them as file assets for easy download and debugging

This is part of every PR on Azure pipelines, and we do'nt plan on publishing this in the github releases, as this can already be downloaded from the marketplace (hence no need to publish in yet another location).
